### ISSUE TITLE
How doing `() => import('./Components/Navbar.vue')` is better than first importing it on the top and using it's name later?

### ISSUE THREAD

**Issue by aasutossh** [MartinsOnuoha/laravel-vue-minimal#1]

**Comment by MartinsOnuoha** [comment]
@aasutossh Good Question. 
This kind of import is called "Lazy" or "Dynamic" import, and the major advantage of dynamic/lazy import is that it makes load time faster. How? 
Whenever we build SPAs like these with vue, webpack bundles all our components into one big blob of javascript file:

bundle.main.js | 4.36 MB
-- | --

Depending on how complex these applications get, the resulting javascript bundle tends to increase in size. What this means for the user is, every time your site is visited, the user's browser needs to download 4.36MB of javascript before they can see anything on your site (even though some of those javascript might not be used immediately). 
The time to download this file may vary depending on the network speed of the user (but that's not something you want to find out, by losing visitors). 

So to mitigate this bundle size, webpack provides "[Code Splitting](https://webpack.js.org/guides/code-splitting/)", which allows us to split our code into smaller chunks and ONLY load the chunk the user needs at the time. so you would end up with a bundle like so:

bundle1.main.js | 7.2 KB
-- | --
bundle2.main.js | 2.2 KB
bundle3.main.js | 5.2 KB
-- | --

In Webpack's word:

> Code splitting is one of the most compelling features of webpack. This feature allows you to split your code into various bundles which can then be loaded on-demand or in parallel. It can be used to achieve smaller bundles and control resource load prioritization which, if used correctly, can have a major impact on load time.

So this isn't just about coding style, but about performance. The Navbar can be conveniently lazy-loaded since it isn't exactly as essential as the page content. 

I hope this answers your question. @aasutossh

**Comment by aasutossh** [comment]
So, is lazy loading everything a bad idea? Or should you lazy load everything? 

Lazy load the things that you don't need right now? I understand the logic behind it, but now I am looking for best practices.

Your reply is too good. Thank you for taking the time to write :).

**Comment by MartinsOnuoha** [comment]
Oh, the best practice with lazy loading is, don't lazy load everything, lol. 
- Would the user need to see this **immediately**? If yes, Don't lazy load.
- Is this component further down the page? If yes, Lazy load
- Is this component essential for initial page content? if No, lazyload it

Basically, lazyload components that you know won't be essential for immediate loading. Also, you can lazy pages as well. 
since your Home page would usually be the first page the user would visit, then you can lazy load pages like "About.vue", "Contact.vue". and so on. This is totally fine.  While pages like "Home.vue" you want to immediately import it and not lazy load it.  
On the Home.vue, even though you immediately import it, you can still lazy load smaller components on that page, like "Carousel.vue", "TestimonialCard.vue".

And so on.

**Comment by aasutossh** [comment]
That's much better. Thank you so much. Where can I learn these things? Currently I write code that just works. I don't give much thought to performance, best practices etc. I want to learn them though.

**Comment by MartinsOnuoha** [comment]
Seems like you're doing great, learning performance would be another advantage under your belt. Here's a link to awesome resources for you on [Frontend Masters](https://frontendmasters.com/learn/vue/). You can check out courses like 
- [Advanced Vuejs Features](https://frontendmasters.com/courses/advanced-vue/) by Evan You
- [Production Grade Vuejs](https://frontendmasters.com/courses/production-vue/) by Ben Hong

Cheers 🎉

**Comment by aasutossh** [comment]
Thank you so much <3. Closing.
